source 'https://github.com/Artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!

target 'GitPeep' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GitPeep
  
  pod 'YYModel'
  
  pod 'YYCache'
  
  pod 'SAMKeychain'
  
  pod 'OcticonsIOS', :git => 'https://github.com/jacksonh/OcticonsIOS.git', :commit => '4bd3b21'
  
  pod 'IQKeyboardManager'
  
  pod 'MKNetworkKit', '0.87'
  
  pod 'MBProgressHUD', '~> 1.1.0'
  
  pod 'MJRefresh'
  
  pod 'SDWebImage'
  
  pod 'GPUImage'
  
  pod 'TYCyclePagerView'
      
  target 'GitPeepTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitPeepUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
